#!/usr/bin/env zsh

# =====================
# | 1.0 |  Path/Vars  |
# =====================
export GHQ_ROOT="{{ .chezmoi.homeDir }}/Developer"
export NVM_DIR="{{ .chezmoi.homeDir }}/.nvm"
  [ -s "/opt/homebrew/opt/nvm/nvm.sh" ] && \. "/opt/homebrew/opt/nvm/nvm.sh"  # This loads nvm
  [ -s "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm" ] && \. "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm"  # This loads nvm bash_completion

if [ -d "/opt/homebrew/opt/ruby/bin" ]; then
  export PATH=/opt/homebrew/opt/ruby/bin:$PATH
  export PATH=`gem environment gemdir`/bin:$PATH
fi

export PATH="/usr/local/opt/libpq/bin:$PATH"
export PATH="/opt/homebrew/opt/libpq/bin:$PATH"

export PNPM_HOME="{{ .chezmoi.homeDir }}/Library/pnpm"
export PATH="/opt/homebrew/opt/python@3.12/libexec/bin:$PATH"
export PATH="/usr/local/go/bin:$GOBIN:$PATH"
# macOS specific configurations
{{ if eq .chezmoi.arch "arm64" -}}
# Apple Silicon
export PATH="/opt/homebrew/bin:$PATH"
source /opt/homebrew/share/zsh-autosuggestions/zsh-autosuggestions.zsh
source /opt/homebrew/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
{{ else -}}
# Intel Mac
export PATH="/usr/local/bin:$PATH"
source /usr/local/share/zsh-autosuggestions/zsh-autosuggestions.zsh
source /usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
{{ end -}}

{{ if eq .chezmoi.os "darwin" -}}
export PATH="/opt/homebrew/opt/openjdk/bin:$PATH"
export DYLD_LIBRARY_PATH="{{ .chezmoi.homeDir }}/.local/lib:$DYLD_LIBRARY_PATH"
export CPATH="$(brew --prefix)/include"
export LIBRARY_PATH="$(brew --prefix)/lib"
{{ end -}}

# Nix daemon
[[ -s "/nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh" ]] && \
  source "/nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh"
# Claude code vars
export ENABLE_BACKGROUND_TASKS=1
export FORCE_AUTO_BACKGROUND_TASKS=1

precmd () { echo -n "\x1b]1337;CurrentDir=$(pwd)\x07" }

# Check if the shell is interactive and if not already in a tmux session
if [[ "$-" == *i* ]] && [[ -z "$TMUX" ]] && [ -x "$(command -v tt)" ]; then
  # Attempt to attach to a session named 'main', or create it if it doesn't exist
  tt attach-session -t main || tt new-session -s main
fi

# =====================
# | 1.1 |  Functions  |
# =====================

# =====================
# | 1.2 |   Aliases   |
# =====================
alias /a="aider"
alias /c="claude"
alias /cr="claude --continue"
alias /g="gemini"
alias /m="mods"
alias /o="opencode"
alias /v="npx vibe-kanban"
alias oc="opencode"

alias gg="lazygit"
alias y="yazi"
alias dd="lazydocker"
alias e="nvim"
alias copy="pbcopy"
alias paste="pbpaste"
alias chrome="/Applications/Google Chrome Dev.app/Contents/MacOS/Google Chrome Dev"
# =====================
# | 1.3 | Keybindings |
# =====================




