#!/usr/bin/env zsh

# =====================
# | 1.0 |  Path/Vars  |
# =====================
[[ -f "$HOME/.config/zsh/shared-cwd.zsh" ]] && source "$HOME/.config/zsh/shared-cwd.zsh"

# =====================
# | 1.1 |  Functions  |
# =====================
function yy() {
	local tmp="$(mktemp -t "yazi-cwd.XXXXXX")" cwd
	yazi "$@" --cwd-file="$tmp"
	if cwd="$(command cat -- "$tmp")" && [ -n "$cwd" ] && [ "$cwd" != "$PWD" ]; then
		builtin cd -- "$cwd"
	fi
	rm -f -- "$tmp"
  zle && zle reset-prompt  # Force prompt redraw
}

# =====================
# | 1.2 |   Aliases   |
# =====================
alias y="yazi"
alias cdl="cd ~/.local/share"
alias mkiso="caligula"
alias j="c"
alias cb="cd -"
alias ..="cd .."
alias cd.="chezmoi cd"
alias cdd="cd $GHQ_ROOT"
alias cdc="cd $XDG_CONFIG_HOME"
alias ls="eza -F -1 --icons=always -T -L=1 -l --group-directories-first --no-user --no-filesize --no-permissions --git --no-time --octal-permissions"
alias lsd="eza -F -1 --icons=always -G -L=1 --no-user --no-filesize --no-permissions --git --no-time --octal-permissions"
alias gls="watch -t eza -F -1 --icons=always -T -L=1 -l --group-directories-first --no-user --no-filesize --no-permissions --git --no-time --octal-permissions"
alias gt='tree -a --prune -I "api|chains|interchaintest|.devcontainer|.github|.aider.*|.devbox|.git|*_test.go|*_templ.go|*.md|node_modules|*.pb.gw.go|.DS_Store|*.pb.go|build|tmp|.wrangler|*.lock|*.pkl.go|*.lockb"'

# =====================
# | 1.3 | Keybindings |
# =====================
zle -N yy-widget yy
bindkey '^F' yy-widget
