#!/usr/bin/env zsh

# =====================
# | 1.0 |  Path/Vars  |
# =====================
export GHQ_ROOT="{{ .chezmoi.homeDir }}/Developer/codebase"
[[ -f /usr/share/zsh-autosuggestions/zsh-autosuggestions.zsh ]] && \
  source /usr/share/zsh-autosuggestions/zsh-autosuggestions.zsh
[[ -f /usr/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh ]] && \
  source /usr/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# Nix profile
[[ -s "{{ .chezmoi.homeDir }}/.nix-profile/etc/profile.d/nix.sh" ]] && \
  source "{{ .chezmoi.homeDir }}/.nix-profile/etc/profile.d/nix.sh"

export LD_LIBRARY_PATH="{{ .chezmoi.homeDir }}/.local/lib:$LD_LIBRARY_PATH"

export PATH="{{ .chezmoi.homeDir }}/.go/bin:{{ .chezmoi.homeDir }}/.go/current/bin:$GOBIN:$PATH"
export PATH="/var/lib/osxcross/bin:$PATH"
export GITHUB_TOKEN="$(gh auth token)"
export PNPM_HOME="{{ .chezmoi.homeDir }}/.local/share/pnpm"
case ":$PATH:" in
  *":$PNPM_HOME:"*) ;;
  *) export PATH="$PNPM_HOME:$PATH" ;;
esac

export NVM_DIR="$HOME/.config/nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

alias copy="wl-copy"
alias paste="wl-paste"
