#!/usr/bin/env zsh

# =====================
# | 1.0 |  Path/Vars  |
# =====================
export PATH="$BUN_INSTALL/bin:$PATH"
[[ -s "$BUN_INSTALL/_bun" ]] && source "$BUN_INSTALL/_bun"
export PATH="{{ .chezmoi.homeDir }}/.deno/bin:$PATH"
[[ -s "{{ .chezmoi.homeDir }}/.deno/env" ]] && source "{{ .chezmoi.homeDir }}/.deno/env"
# =====================
# | 1.1 |  Functions  |
# =====================

# =====================
# | 1.2 |   Aliases   |
# =====================
alias p="pnpm"
alias nrb="npm run build"
alias nrs="npm run start"
alias nrd="npm run dev"
alias nrt="npm run test"

# =====================
# | 1.3 | Keybindings |
# =====================

