#!/usr/bin/env zsh

# =====================
# | 1.0 |  Path/Vars  |
# =====================

# =====================
# | 1.1 |  Functions  |
# =====================

# =====================
# | 1.2 |   Aliases   |
# =====================
alias oc="opencode"
alias /o="opencode"
alias /oc="opencode --continue"
# =====================
# | 1.3 | Keybindings |
# =====================
