#!/usr/bin/env zsh

# =====================
# | 1.0 |  Path/Vars  |
# =====================
export PATH="{{ .chezmoi.homeDir }}/.local/bin:$PATH"
export PATH="{{ .chezmoi.homeDir }}/.egit/.venv/bin:$PATH"
# =====================
# | 1.1 |  Functions  |
# =====================

# =====================
# | 1.2 |   Aliases   |
# =====================

# =====================
# | 1.3 | Keybindings |
# =====================
# Virtual environment for specific tools
