# TPM - Tmux Plugin Manager
[".config/nvim"]
type = "git-repo"
url = "https://github.com/prnk28/nvim.git"
refreshPeriod = "1m"

[".zgen"]
type = "git-repo"
url = "https://github.com/tarjoilija/zgen.git"
refreshPeriod = "12h"
