# TPM - Tmux Plugin Manager
[".config/nvim"]
type = "git-repo"
url = "https://github.com/prnk28/nvim.git"
refreshPeriod = "1m"
[".config/nvim".pull]
    args = ["--force", "--rebase"]

[".zgen"]
type = "git-repo"
url = "https://github.com/tarjoilija/zgen.git"
refreshPeriod = "12h"
