# https://taskfile.dev

version: "3"
tasks:
  default:
    cmds:
      - task: setup-git
      - stow config -t $XDG_CONFIG_HOME
    silent: true

  setup-git:
    desc: Setup git
    cmds:
      - git config --global user.name "Prad N"
      - git config --global user.email "prad@didao.xyz"
      - git config --global core.editor "nvim"
      - gh alias import ./aliases.yml --clobber
    silent: true
