version: '3.8'

services:
  n8n:
    image: docker.n8n.io/n8nio/n8n:latest
    container_name: n8n
    ports:
      - "${N8N_PORT:-5678}:5678"
    environment:
      # Basic Configuration
      - N8N_HOST=${N8N_HOST:-localhost}
      - N8N_PORT=5678
      - N8N_PROTOCOL=${N8N_PROTOCOL:-http}

      # Security
      - N8N_BASIC_AUTH_ACTIVE=${N8N_BASIC_AUTH_ACTIVE:-false}
      - N8N_BASIC_AUTH_USER=${N8N_BASIC_AUTH_USER}
      - N8N_BASIC_AUTH_PASSWORD=${N8N_BASIC_AUTH_PASSWORD}

      # Database Configuration
      - DB_TYPE=${DB_TYPE:-sqlite}
      - DB_SQLITE_VACUUM_ON_STARTUP=${DB_SQLITE_VACUUM_ON_STARTUP:-false}

      # Execution Mode
      - EXECUTIONS_MODE=${EXECUTIONS_MODE:-regular}
      - EXECUTIONS_PROCESS=${EXECUTIONS_PROCESS:-main}

      # Timezone
      - GENERIC_TIMEZONE=${GENERIC_TIMEZONE:-America/New_York}
      - TZ=${TZ:-America/New_York}

      # Webhook Configuration
      - WEBHOOK_URL=${WEBHOOK_URL:-http://localhost:5678/}

      # Additional Features
      - N8N_METRICS=${N8N_METRICS:-false}
      - N8N_VERSION_NOTIFICATIONS_ENABLED=${N8N_VERSION_NOTIFICATIONS_ENABLED:-true}
      - N8N_DIAGNOSTICS_ENABLED=${N8N_DIAGNOSTICS_ENABLED:-false}
    volumes:
      - ./data:/home/node/.n8n
      - ./files:/files
    restart: unless-stopped
    networks:
      - n8n-network

networks:
  n8n-network:
    driver: bridge

volumes:
  n8n_data:
    driver: local