[metadata]
name = "repos"
description = "A channel to select Github repos"
requirements = ["gh", "ghq", "nvim"]

[source]
command = "ghq list"

[preview]
command = "gh repo view '{}'"

[ui]
preview_panel = { "size" = 70, "scrollbar" = true }

[keybindings]
shortcut = "f2"
enter = "actions:edit"

[actions.edit]
command = "cd $GHQ_ROOT/{} && nvim ."
description = "Open Repo"
