[general]
import = ["~/.config/alacritty/themes/cyberdream.toml"]
live_config_reload = true
working_directory = "/Users/prad/Developer"

# Tell Alacritty to run the ssh client directly.
# [terminal.shell]
# program = "/usr/bin/ssh"
# args = ["-C", "code"]
#
[terminal.shell]
program = "/bin/zsh"
args = ["-l"]

[window]
dynamic_padding = false
decorations = "Buttonless"
opacity = 0.85
blur = false
option_as_alt = "Both"

[window.dimensions]
columns = 0
lines = 0

[font]
size = 19

[font.bold]
family = "VictorMono Nerd Font Mono"
style = "Light"

[font.bold_italic]
family = "VictorMono Nerd Font Mono"
style = "Light Italic"

[font.italic]
family = "VictorMono Nerd Font Mono"
style = "ExtraLight Italic"

[font.normal]
family = "VictorMono Nerd Font Mono"
style = "ExtraLight"

[mouse]
hide_when_typing = true
bindings = [{ mouse = "Right", mods = "Control", action = "Paste" }]

[colors.cursor]
cursor = "0xd8d8d8"
text = "0x181818"

[[keyboard.bindings]]
key = "Left"
mods = "Command"
chars = "\u001bOH"

[[keyboard.bindings]]
key = "Right"
mods = "Command"
chars = "\u001bOF"

[[keyboard.bindings]]
key = "Up"
mods = "Command"
chars = "\u001b[1;5H"

[[keyboard.bindings]]
key = "Down"
mods = "Command"
chars = "\u001b[1;5F"

[[keyboard.bindings]]
key = "S"
mods = "Command"
chars = "\u0013" # This represents Ctrl+S

[[keyboard.bindings]]
key = "N"
mods = "Command|Shift"
action = "CreateNewWindow" # This represents Ctrl+S

[[keyboard.bindings]]
key = "C"
mods = "Command"
action = "Copy"  # System clipboard copy

[[keyboard.bindings]]
key = "V"
mods = "Command"
action = "Paste" # System clipboard paste

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"
save_to_clipboard = true                      # Automatically copy selection to system clipboard
