[general]
import = ["~/.config/alacritty/themes/cyberdream.toml"]
live_config_reload = true
working_directory = "/Users/prad/Developer"

# Tell Alacritty to run the ssh client directly.
# [terminal.shell]
# program = "/usr/bin/ssh"
# args = ["-C", "code"]
#
[terminal.shell]
program = "/bin/zsh"
args = ["-l"]

[window]
dynamic_padding = false
decorations = "Buttonless"
opacity = 0.85
blur = false
option_as_alt = "Both"

[window.dimensions]
columns = 0
lines = 0

[font]
size = 19

[font.bold]
family = "VictorMono Nerd Font Mono"
style = "Light"

[font.bold_italic]
family = "VictorMono Nerd Font Mono"
style = "Light Italic"

[font.italic]
family = "VictorMono Nerd Font Mono"
style = "ExtraLight Italic"

[font.normal]
family = "VictorMono Nerd Font Mono"
style = "ExtraLight"

[mouse]
hide_when_typing = true
bindings = [{ mouse = "Right", mods = "Control", action = "Paste" }]

[colors.cursor]
cursor = "0xd8d8d8"
text = "0x181818"

[[keyboard.bindings]]
key = "F"
mods = "Command|Shift"
chars = "\u0002F"

[[keyboard.bindings]]
key = "Left"
mods = "Command"
chars = "\u001bOH"

[[keyboard.bindings]]
key = "Right"
mods = "Command"
chars = "\u001bOF"

[[keyboard.bindings]]
key = "Up"
mods = "Command"
chars = "\u001b[1;5H"

[[keyboard.bindings]]
key = "Down"
mods = "Command"
chars = "\u001b[1;5F"

[[keyboard.bindings]]
key = "R"
mods = "Command|Shift"
chars = "\u0002r"

[[keyboard.bindings]]
key = ","
mods = "Command"
chars = "\u0002,"

[[keyboard.bindings]]
key = "H"
mods = "Command|Shift"
chars = "\u0002H"

[[keyboard.bindings]]
key = "J"
mods = "Command|Shift"
chars = "\u0002J"

[[keyboard.bindings]]
key = "K"
mods = "Command"
chars = "\u0002o"

[[keyboard.bindings]]
key = "K"
mods = "Command|Shift"
chars = "\u0002K"

[[keyboard.bindings]]
key = "L"
mods = "Command|Shift"
chars = "\u0002L"

[[keyboard.bindings]]
key = "O"
mods = "Command"
chars = "\u0002o"

[[keyboard.bindings]]
key = "T"
mods = "Command|Shift"
chars = "\u0002T"

[[keyboard.bindings]]
key = "["
mods = "Command"
chars = "\u0002["

[[keyboard.bindings]]
key = "]"
mods = "Command"
chars = "\u0002]"

[[keyboard.bindings]]
key = "I"
mods = "Command"
chars = "\u0002N"

[[keyboard.bindings]]
key = "u"
mods = "Command"
chars = "\u0002U"

# Yazi Open
[[keyboard.bindings]]
key = "."
mods = "Command"
chars = "\u0002."

# Letf/Right Tabs
[[keyboard.bindings]]
key = ","
mods = "Command|Shift"
chars = "\u0002p"

[[keyboard.bindings]]
key = "E"
mods = "Control"
chars = "\u0005"

[[keyboard.bindings]]
key = "L"
mods = "Command"
chars = "\u0002t"

[[keyboard.bindings]]
key = "1"
mods = "Command"
chars = "\u00020"

[[keyboard.bindings]]
key = "2"
mods = "Command"
chars = "\u00021"

[[keyboard.bindings]]
key = "3"
mods = "Command"
chars = "\u00022"

[[keyboard.bindings]]
key = "4"
mods = "Command"
chars = "\u00023"

[[keyboard.bindings]]
key = "5"
mods = "Command"
chars = "\u00024"

[[keyboard.bindings]]
key = "6"
mods = "Command"
chars = "\u00025"

[[keyboard.bindings]]
key = "7"
mods = "Command"
chars = "\u00026"

[[keyboard.bindings]]
key = "8"
mods = "Command"
chars = "\u00027"

[[keyboard.bindings]]
key = "9"
mods = "Command"
chars = "\u00028"

[[keyboard.bindings]]
key = "A"
mods = "Command"
chars = "\u0001" # This represents Ctrl+A

[[keyboard.bindings]]
key = "S"
mods = "Command"
chars = "\u0013" # This represents Ctrl+S

[[keyboard.bindings]]
key = "Q"
mods = "Command"
chars = "\u0002x" # Maps to tmux copy mode

[[keyboard.bindings]]
key = "T"
mods = "Command"
chars = "\u0002t"

[[keyboard.bindings]]
key = "N"
mods = "Command|Shift"
action = "CreateNewWindow" # This represents Ctrl+S

[[keyboard.bindings]]
key = "C"
mods = "Command"
action = "Copy"  # System clipboard copy

[[keyboard.bindings]]
key = "V"
mods = "Command"
action = "Paste" # System clipboard paste

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"
save_to_clipboard = true                      # Automatically copy selection to system clipboard

[[keyboard.bindings]]
key = "G"
mods = "Command"
chars = "\u0002\u001bg" # This represents tmux prefix (<C-b>) followed by Alt+g

[[keyboard.bindings]]
key = "G"
mods = "Command|Shift"
chars = "\u0002\u001bv" # This represents tmux prefix (<C-b>) followed by Alt+g


[[keyboard.bindings]]
key = "D"
mods = "Command"
chars = "\u0002\u001bD" # This represents tmux prefix (<C-b>) followed by Alt+g

[[keyboard.bindings]]
key = "S"
mods = "Command|Shift"
chars = "\u0002\u001br" # This represents tmux prefix (<C-b>) followed by Alt+g

[[keyboard.bindings]]
key = "P"
mods = "Command"
chars = "\u0002\u001bs" # This represents tmux prefix (<C-b>) followed by Alt+g

[[keyboard.bindings]]
key = "W"
mods = "Command"
chars = "\u0003" # Control-C character

[[keyboard.bindings]]
key = "W"
mods = "Command"
chars = "\u0018" # This sends Ctrl+X

[[keyboard.bindings]]
key = "E"
mods = "Command"
chars = "\u0005" # Control-E character

[[keyboard.bindings]]
key = "Space"
mods = "Control"
chars = "\u0002o" # Maps to tmux copy mode

[[keyboard.bindings]]
key = "Tab"
mods = "Control"
chars = "\u0002@" # Maps to tmux copy mode

[[keyboard.bindings]]
key = "R"
mods = "Command"
chars = "\u0002R" # Maps to tmux copy mode

[[keyboard.bindings]]
key = "J"
mods = "Control|Shift"
chars = "\u0002z"      # Maps to tmux copy mode

[[keyboard.bindings]]
key = ","
mods = "Command"
chars = "\u0002," # Maps to tmux copy mode

[[keyboard.bindings]]
key = "Enter"
mods = "Shift"
chars = "\u001b\r"
