[general]
live_config_reload = true
working_directory = "/home/prad/code"

[terminal.shell]
program = "/bin/zsh"
args = ["-l"]

[window]
blur = true
dynamic_padding = true
decorations = "Buttonless"
opacity = 0.69
option_as_alt = "Both"

[font]
size = 11

[font.bold]
family = "VictorMono Nerd Font Mono"
style = "Light"

[font.bold_italic]
family = "VictorMono Nerd Font Mono"
style = "Light Italic"

[font.italic]
family = "VictorMono Nerd Font Mono"
style = "ExtraLight Italic"

[font.normal]
family = "VictorMono Nerd Font Mono"
style = "ExtraLight"

[mouse]
hide_when_typing = true
bindings = [{ mouse = "Right", mods = "Control", action = "Paste" }]

[[keyboard.bindings]]
key = "E"
mods = "Control"
chars = "\u0005"

[[keyboard.bindings]]
key = "C"
mods = "Option"
action = "Copy"

[[keyboard.bindings]]
key = "V"
mods = "Option"
action = "Paste"

[[keyboard.bindings]]
key = "C"
mods = "Command"
action = "Copy"

[[keyboard.bindings]]
key = "C"
mods = "Super"
action = "Copy"

[[keyboard.bindings]]
key = "V"
mods = "Super"
action = "Paste"

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"
save_to_clipboard = true                      # Automatically copy selection to system clipboard

[[keyboard.bindings]]
key = "Enter"
mods = "Shift"
chars = "\u001b\r"

# Disable Command-N (new window) - macOS default
[[keyboard.bindings]]
key = "N"
mods = "Command"
action = "CreateNewWindow"

# Disable Command-T (new tab) - macOS default
[[keyboard.bindings]]
key = "T"
mods = "Command"
chars = "\u0002t" # This sends Ctrl+B which and t as chars for tmux

[[keyboard.bindings]]
key = "H"
mods = "Super"
chars = "\u0002[" # This sends Ctrl+B which and t as chars for tmux

[[keyboard.bindings]]
key = "L"
mods = "Super"
chars = "\u0002]" # This sends Ctrl+B which and t a

[[keyboard.bindings]]
key = "K"
mods = "Super"
chars = "\u0002k"

[[keyboard.bindings]]
key = "J"
mods = "Super"
chars = "\u0002J"

[[keyboard.bindings]]
key = "Enter"
mods = "Super"
chars = "\u0002o"

[[keyboard.bindings]]
key = "D"
mods = "Super"
action = "None"

[[keyboard.bindings]]
key = "Tab"
mods = "Super"
chars = "\u001a" # This sends Ctrl+Z which is the standard suspend signal
