import = ["~/.config/alacritty/themes-2/gotham.toml"]

live_config_reload = true

[env]
TERM = "xterm-256color"

[shell]
program = "/usr/bin/ssh"
args = ["prad@192.168.2.118"]

[window]
decorations = "Buttonless"
dynamic_padding = true
opacity = 0.80
blur = false
option_as_alt = "Both"
startup_mode = "Windowed"

[window.dimensions]
columns = 0
lines = 0

[window.padding]
x = 0
y = 0

[font]
size = 15

[font.bold]
family = "VictorMono Nerd Font"
style = "Light"

[font.bold_italic]
family = "VictorMono Nerd Font"
style = "Light Italic"

[font.italic]
family = "VictorMono Nerd Font"
style = "ExtraLight Italic"

[font.normal]
family = "VictorMono Nerd Font"
style = "ExtraLight"

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"
save_to_clipboard = true

[mouse]
hide_when_typing = true
bindings = [{ mouse = "Right", mods = "Control", action = "Paste" }]

[colors.cursor]
cursor = "0xd8d8d8"
text = "0x181818"

[[keyboard.bindings]]
key = "Left"
mods = "Command"
chars = "\u001bOH"

[[keyboard.bindings]]
key = "Right"
mods = "Command"
chars = "\u001bOF"


[[keyboard.bindings]]
key = "Up"
mods = "Command"
chars = "\u001b[1;5H"

[[keyboard.bindings]]
key = "Down"
mods = "Command"
chars = "\u001b[1;5F"

[[keyboard.bindings]]
key = "K"
mods = "Command"
chars = "\u0002K"

[[keyboard.bindings]]
key = "Tab"
mods = "Control"
chars = "\u0002O"

[[keyboard.bindings]]
key = "J"
mods = "Command"
chars = "\u0002J"

[[keyboard.bindings]]
key = "J"
mods = "Command|Shift"
chars = "\u0002z"

[[keyboard.bindings]]
key = "D"
mods = "Command"
chars = "\u0002w"

[[keyboard.bindings]]
key = ","
mods = "Command"
chars = "\u0002r"

[[keyboard.bindings]]
key = "["
mods = "Command"
chars = "\u0002h"

[[keyboard.bindings]]
key = "]"
mods = "Command"
chars = "\u0002l"

[[keyboard.bindings]]
key = "{"
mods = "Command|Shift"
chars = "\u0002j"

[[keyboard.bindings]]
key = "}"
mods = "Command|Shift"
chars = "\u0002k"

[[keyboard.bindings]]
key = "O"
mods = "Command"
chars = "\u0002O"

[[keyboard.bindings]]
key = "T"
mods = "Command"
chars = "\u0002t"

[[keyboard.bindings]]
key = "1"
mods = "Command"
chars = "\u00020"

[[keyboard.bindings]]
key = "2"
mods = "Command"
chars = "\u00021"

[[keyboard.bindings]]
key = "3"
mods = "Command"
chars = "\u00022"

[[keyboard.bindings]]
key = "4"
mods = "Command"
chars = "\u00023"

[[keyboard.bindings]]
key = "5"
mods = "Command"
chars = "\u00024"

[[keyboard.bindings]]
key = "6"
mods = "Command"
chars = "\u00025"

[[keyboard.bindings]]
key = "7"
mods = "Command"
chars = "\u00026"

[[keyboard.bindings]]
key = "8"
mods = "Command"
chars = "\u00027"

[[keyboard.bindings]]
key = "9"
mods = "Command"
chars = "\u00028"

[[keyboard.bindings]]
key = "g"
mods = "Command"
chars = "\u0002G"

[[keyboard.bindings]]
key = "f"
mods = "Command"
chars = "\u0002F"

[[keyboard.bindings]]
key = "u"
mods = "Command"
chars = "\u0002U"

[[keyboard.bindings]]
key = "Enter"
mods = "Command"
chars = "\u0002O"

[[keyboard.bindings]]
key = "Enter"
mods = "Control"
chars = "\u0002O"

[[keyboard.bindings]]
key = "Space"
mods = "Option"
chars = "\u0002O"

[[keyboard.bindings]]
key = "Q"
mods = "Command"
chars = "\u0002x"

[[keyboard.bindings]]
key = ","
mods = "Command"
chars = "\u0002M"

[[keyboard.bindings]]
key = "."
mods = "Command"
chars = "\u0002."

# Additions for remapping PgUp to Home and PgDown to End
[[keyboard.bindings]]
key = "PageUp"
chars = "\u001b[H"

[[keyboard.bindings]]
key = "PageDown"
chars = "\u001b[F"

# Neovim bindings for top of page and bottom of page
[[keyboard.bindings]]
key = "PageUp"
mods = "Shift"
chars = "gg"

[[keyboard.bindings]]
key = "PageDown"
mods = "Shift"
chars = "G"

# Additions for remapping Command-w to Ctrl-w and Command-Shift-w to Ctrl-Shift-w
[[keyboard.bindings]]
key = "W"
mods = "Command"
chars = "\u0003w"

[[keyboard.bindings]]
key = "W"
mods = "Command|Shift"
chars = "\u001b[1;5W"
