[general]
live_config_reload = true
working_directory = "/home/prad/code/github.com/sonr-io/sonr"

[terminal.shell]
program = "/bin/zsh"
args = ["-l", "-c", "claude"]

[window]
blur = false
dynamic_padding = true
decorations = "Buttonless"
opacity = 0.9
option_as_alt = "Both"

[font]
size = 12

[font.bold]
family = "JetbrainsMonoNL Nerd Font Mono"
style = "ExtraLight"

[font.bold_italic]
family = "JetbrainsMonoNL Nerd Font Mono"
style = "ExtraLight Italic"

[font.italic]
family = "JetbrainsMonoNL Nerd Font Mono"
style = "Thin Italic"

[font.normal]
family = "JetbrainsMonoNL Nerd Font Mono"
style = "Thin"


[mouse]
hide_when_typing = true
bindings = [{ mouse = "Right", mods = "Control", action = "Paste" }]

[[keyboard.bindings]]
key = "E"
mods = "Control"
chars = "\u0005"

[[keyboard.bindings]]
key = "C"
mods = "Option"
action = "Copy"

[[keyboard.bindings]]
key = "V"
mods = "Option"
action = "Paste"

[[keyboard.bindings]]
key = "C"
mods = "Command"
action = "Copy"

[[keyboard.bindings]]
key = "C"
mods = "Super"
action = "Copy"

[[keyboard.bindings]]
key = "V"
mods = "Super"
action = "Paste"

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"
save_to_clipboard = true                      # Automatically copy selection to system clipboard

[[keyboard.bindings]]
key = "Enter"
mods = "Shift"
chars = "\u001b\r"

[[keyboard.bindings]]
key = "H"
mods = "Alt"
action = "None"

[[keyboard.bindings]]
key = "L"
mods = "Alt"
action = "None"

# Disable Command-N (new window) - macOS default
[[keyboard.bindings]]
key = "N"
mods = "Command"
action = "CreateNewWindow"

# Disable Command-T (new tab) - macOS default
[[keyboard.bindings]]
key = "T"
mods = "Command"
action = "None"

# Disable Command-N (new window) - macOS default
[[keyboard.bindings]]
key = "N"
mods = "Super"
action = "None"

# Disable Command-T (new tab) - macOS default
[[keyboard.bindings]]
key = "T"
mods = "Super"
action = "None"

[[keyboard.bindings]]
key = "J"
mods = "Alt"
action = "None"

[[keyboard.bindings]]
key = "K"
mods = "Alt"
action = "None"
