[general]
live_config_reload = true

[terminal.shell]
program = "/bin/zsh"
args = ["-l", "-c", "yazi"]

[window]
blur = true
dynamic_padding = false
decorations = "Buttonless"
opacity = 0.95
option_as_alt = "Both"

[font]
size = 12.5

[font.bold]
family = "VictorMono Nerd Font Mono"
style = "Light"

[font.bold_italic]
family = "VictorMono Nerd Font Mono"
style = "Light Italic"

[font.italic]
family = "VictorMono Nerd Font Mono"
style = "ExtraLight Italic"

[font.normal]
family = "VictorMono Nerd Font Mono"
style = "ExtraLight"

[mouse]
hide_when_typing = true
bindings = [{ mouse = "Right", mods = "Control", action = "Paste" }]

[colors.cursor]
cursor = "0xd8d8d8"
text = "0x181818"

[[keyboard.bindings]]
key = "E"
mods = "Control"
chars = "\u0005"

[[keyboard.bindings]]
key = "C"
mods = "Option"
action = "Copy"

[[keyboard.bindings]]
key = "V"
mods = "Option"
action = "Paste"

[[keyboard.bindings]]
key = "C"
mods = "Command"
action = "Copy"

[[keyboard.bindings]]
key = "C"
mods = "Super"
action = "Copy"

[[keyboard.bindings]]
key = "V"
mods = "Super"
action = "Paste"

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"
save_to_clipboard = true                      # Automatically copy selection to system clipboard

[[keyboard.bindings]]
key = "Enter"
mods = "Shift"
chars = "\u001b\r"

[[keyboard.bindings]]
key = "H"
mods = "Alt"
action = "None"

[[keyboard.bindings]]
key = "L"
mods = "Alt"
action = "None"

# Disable Command-N (new window) - macOS default
[[keyboard.bindings]]
key = "N"
mods = "Command"
action = "CreateNewWindow"

# Disable Command-T (new tab) - macOS default
[[keyboard.bindings]]
key = "T"
mods = "Command"
action = "None"

# Disable Command-N (new window) - macOS default
[[keyboard.bindings]]
key = "N"
mods = "Super"
action = "None"

# Disable Command-T (new tab) - macOS default
[[keyboard.bindings]]
key = "T"
mods = "Super"
action = "None"

[[keyboard.bindings]]
key = "J"
mods = "Alt"
action = "None"

[[keyboard.bindings]]
key = "K"
mods = "Alt"
action = "None"
